### ISSUE TITLE
Main window empty after update to version 1.15.1006

### ISSUE THREAD

**Issue by mdenzin** [tom-englert/ResXResourceManager#116]
The main window is empty after update to new version. Standalone version is working.
Using VS 2015. Latest .NET Framework installed is 4.7.1.

**Comment by tom-englert** [comment]
Please provide output

**Comment by Dwargh** [comment]
Yeah, this:
![image](https://user-images.githubusercontent.com/8590370/38549433-48b03eca-3cb4-11e8-9cf8-a5d2c1691284.png)

**Comment by Xgleich8** [comment]
I have the same problem VS 2017 (15.6.5) .Net 4.7.02558 and VS crashed after clicking other tab in ResXManager.

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Windows.FreezableCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Cast(System.Object)
   at System.Windows.FreezableCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].System.Collections.IList.Add(System.Object)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(System.Object, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(System.Object, System.Xaml.XamlType, System.Object, System.Xaml.XamlType)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(System.Xaml.XamlReader, System.Xaml.XamlObjectWriter)
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(System.Xaml.XamlObjectWriter)
   at System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(System.Windows.DependencyObject, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector, System.Collections.Generic.List`1<System.Windows.DependencyObject>, System.Windows.UncommonField`1<System.Collections.Hashtable>)
   at System.Windows.FrameworkTemplate.LoadContent(System.Windows.DependencyObject, System.Collections.Generic.List`1<System.Windows.DependencyObject>)
   at System.Windows.StyleHelper.ApplyTemplateContent(System.Windows.UncommonField`1<System.Collections.Specialized.HybridDictionary[]>, System.Windows.DependencyObject, System.Windows.FrameworkElementFactory, Int32, System.Collections.Specialized.HybridDictionary, System.Windows.FrameworkTemplate)
   at System.Windows.FrameworkTemplate.ApplyTemplateContent(System.Windows.UncommonField`1<System.Collections.Specialized.HybridDictionary[]>, System.Windows.FrameworkElement)
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)

**Comment by Xgleich8** [comment]
![vs1](https://user-images.githubusercontent.com/33786825/38552160-8c010d60-3cbb-11e8-8e32-aca0c53057fe.png)
C:\Users\username\AppData\Local\Microsoft\VisualStudio\15.0_5b7e72d3\Extensions\h003bzrq.031\System.Windows.Interactivity.dll

and

![vs2](https://user-images.githubusercontent.com/33786825/38552276-f3d94c4a-3cbb-11e8-8242-f08b7a28a171.png)

I have deleted the .vs folder within the solution and it now works again

**Comment by Dwargh** [comment]
now I got this:

Error: Loader errors at start:
Assembly: Microsoft.Expression.Interactions.dll => GenericArguments[0], 'System.Object', on 'System.Windows.Interactivity.TargetedTriggerAction`1[T]' violates the constraint of type parameter 'T'.: 
GenericArguments[0], 'System.Object', on 'System.Windows.Interactivity.TargetedTriggerAction`1[T]' violates the constraint of type parameter 'T'.: 
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception. ---> System.ArgumentException: Cannot add instance of type 'CommandRoutingBehavior' to a collection of type 'BehaviorCollection'. Only items of type 'T' are allowed.
   at System.Windows.FreezableCollection`1.Cast(Object value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml:line 1
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView..ctor(ExportProvider exportProvider, ThemeManager themeManager) in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml.cs:line 40
Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.TriggerCollection' threw an exception. ---> System.TypeLoadException: Could not load type 'System.Windows.Interactivity.PreviewInvokeEventArgs' from assembly 'System.Windows.Interactivity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger.OnAttached()
   at System.Windows.Interactivity.TriggerBase.Attach(DependencyObject dependencyObject)
   at System.Windows.Interactivity.TriggerCollection.ItemAdded(TriggerBase item)
   at System.Windows.Interactivity.AttachableCollection`1.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.FreezableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.FreezableCollection`1.OnCollectionChanged(NotifyCollectionChangedAction action, Int32 oldIndex, T oldValue, Int32 newIndex, T newValue)
   at System.Windows.FreezableCollection`1.AddHelper(T value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml:line 1
   at tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ICompositionHost compositionHost) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:line 55
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.View.Visuals.TranslationsView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\TranslationsView.xaml:line 1
   at tomenglertde.ResXManager.View.Visuals.TranslationsView..ctor(ExportProvider exportProvider) in C:\Agent\_work\9\s\ResXManager.View\Visuals\TranslationsView.xaml.cs:line 33
Assembly location: C:\Users\username\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\iazvp2ij.3cx
Version: 1.15.1006.0
.NET Framework Version: 461308 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)

**Comment by mdenzin** [comment]
Got th same error message in output as Dwargh. When I copy an older version of System.Windows.Interactivity to the Resx folder I can see the tabs. Main tab is still empty but the
content on configuration and languages tab is visible .

**Comment by mdenzin** [comment]
Sorry. Wrong button.

**Comment by tom-englert** [comment]
@mdenzin can you start another VS and list all assemblies, to see what versions of System.Windows.Interactivity are loaded:
https://stackoverflow.com/questions/458362/how-do-i-list-all-loaded-assemblies#458390

**Comment by mdenzin** [comment]
R# Ultimate 2016.1.1 with System.Windows.Interactivity.dll Version  1.01340.0.
Version from Resx Folder = 3.0.40218.0

**Comment by tom-englert** [comment]
Now that's a really outdated version of R#

**Comment by Xgleich8** [comment]
It's not work for me. I have no other Extension with Reference to **System.Windows.Interactivity.dll**

Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception. ---> System.ArgumentException: Cannot add instance of type 'EntityFilter' to a collection of type 'BehaviorCollection'. Only items of type 'T' are allowed.
   at System.Windows.FreezableCollection`1.Cast(Object value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml:line 1
   at tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ICompositionHost compositionHost) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:line 55

**Comment by tom-englert** [comment]
@Xgleich8 can you try the latest build from http://vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a/

**Comment by Dwargh** [comment]
I get this error with the above mentioned build

```
Error: System.Windows.Markup.XamlParseException: Collection property 'Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger'.'Actions' is null. ---> System.Xaml.XamlObjectWriterException: Collection property 'Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger'.'Actions' is null.
   at System.Xaml.XamlObjectWriter.WriteGetObject()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml:line 1
   at tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ICompositionHost compositionHost) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:line 55
```

**Comment by tom-englert** [comment]
@Dwargh nothing else in the log?

**Comment by Dwargh** [comment]
I tried the newest version.  still empty window.
This is what's in the output.
```
Init: 328 ms
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: C:\Users\username\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\1233dqai.13g
Version: 1.15.1043.0
.NET Framework Version: 461308 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
Resolved Microsoft.Expression.Interactions, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 from file:///C:/Users/username/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/1233dqai.13g/Microsoft.Expression.Interactions.dll
<The above mentioned Error>
<list of found assemblies>
<list of loaded assemblies>
```

**Comment by tom-englert** [comment]
@Dwargh unfortunately you have clipped the essential part of the output. Please attach the full output.

**Comment by Dwargh** [comment]
Tried the newest release. got the same error
```
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: C:\Users\Andreas\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\vw5ezwzo.olj
Version: 1.16.1044.0
.NET Framework Version: 461308 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
Found assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' already loaded from file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/Newtonsoft.Json.DLL.
Found assembly 'System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' already loaded from file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/System.Windows.Interactivity.DLL.
Found assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' already loaded from file:///C:/Users/Andreas/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14_000/Newtonsoft.Json.DLL.
Found assembly 'JetBrains.Annotations, Version=11.1.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' already loaded from file:///C:/Users/Andreas/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14_000/JetBrains.Annotations.DLL.
Found assembly 'System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' already loaded from file:///C:/Users/Andreas/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14_000/System.Windows.Interactivity.dll.
Loaded assembly 'DataGridExtensions, Version=1.0.37.0, Culture=neutral, PublicKeyToken=43de855f87de903a' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/DataGridExtensions.dll.
Loaded assembly 'JetBrains.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/JetBrains.Annotations.dll.
Loaded assembly 'Microsoft.Expression.Interactions, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/Microsoft.Expression.Interactions.dll.
Loaded assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/Newtonsoft.Json.dll.
Loaded assembly 'ResXManager.Infrastructure, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/ResXManager.Infrastructure.DLL.
Loaded assembly 'ResXManager.Model, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/ResXManager.Model.DLL.
Loaded assembly 'ResXManager.Translators, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/ResXManager.Translators.dll.
Loaded assembly 'ResXManager.View, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/ResXManager.View.dll.
Loaded assembly 'ResXManager.VSIX, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/ResXManager.VSIX.dll.
Loaded assembly 'System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' from file:///C:/Users/Andreas/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14_000/System.Windows.Interactivity.dll.
Loaded assembly 'TomsToolbox.Core, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/TomsToolbox.Core.DLL.
Loaded assembly 'TomsToolbox.Desktop, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/TomsToolbox.Desktop.DLL.
Loaded assembly 'TomsToolbox.ObservableCollections, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/TomsToolbox.ObservableCollections.DLL.
Loaded assembly 'TomsToolbox.Wpf, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/TomsToolbox.Wpf.DLL.
Loaded assembly 'TomsToolbox.Wpf.Styles, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/TomsToolbox.Wpf.Styles.DLL.
Resolved Microsoft.Expression.Interactions, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 from file:///C:/Users/Andreas/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw5ezwzo.olj/Microsoft.Expression.Interactions.dll
Error: System.Windows.Markup.XamlParseException: Collection property 'Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger'.'Actions' is null. ---> System.Xaml.XamlObjectWriterException: Collection property 'Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger'.'Actions' is null.
   at System.Xaml.XamlObjectWriter.WriteGetObject()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml:line 1
   at tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ICompositionHost compositionHost) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:line 55
```
uninstalled and installed v1.14 instead.

**Comment by tom-englert** [comment]
@Dwargh very obvious:
```
Found assembly 'System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' already loaded from file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/System.Windows.Interactivity.DLL.
Found assembly 'System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' already loaded from file:///C:/Users/Andreas/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14_000/System.Windows.Interactivity.dll.
```
=> remove the one from PrivateAssemblies

**Comment by Dwargh** [comment]
thank you for your patience with me.
