### ISSUE TITLE
ResXManager not working in VS 2017 15.6.6

### ISSUE THREAD

**Issue by judick341** [tom-englert/ResXResourceManager#117]
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception. ---> System.ArgumentException: Cannot add instance of type 'CommandRoutingBehavior' to a collection of type 'BehaviorCollection'. Only items of type 'T' are allowed.
   at System.Windows.FreezableCollection`1.Cast(Object value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml:line 1
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView..ctor(ExportProvider exportProvider, ThemeManager themeManager) in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml.cs:line 40
Assembly location: C:\Users\dick\AppData\Local\Microsoft\VisualStudio\15.0_4ca776c5\Extensions\dbuhyrde.jtm
Version: 1.15.1006.0
.NET Framework Version: 461310 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)

**Comment by tom-englert** [comment]
@judick341 Can you try the latest build from http://vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a/

**Comment by judick341** [comment]
I installed the latest build, unfortunately it is not working too. Here is the message from VS 2017 15.6.6.
It seems that this is not a general problem of ResXManager, since it is working in the same VS2017 on the computer of a colleague?!

ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception. ---> System.ArgumentException: Cannot add instance of type 'CommandRoutingBehavior' to a collection of type 'BehaviorCollection'. Only items of type 'T' are allowed.
   at System.Windows.FreezableCollection`1.Cast(Object value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml:line 1
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView..ctor(ExportProvider exportProvider, ThemeManager themeManager) in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml.cs:line 40
Assembly location: C:\Users\dick\AppData\Local\Microsoft\VisualStudio\15.0_4ca776c5\Extensions\0lwnynqe.krc
Version: 1.15.1035.0
.NET Framework Version: 461310 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)

**Comment by tom-englert** [comment]
@judick341 there's another update, can you try it?

**Comment by Xgleich8** [comment]
Could limit the problem even further: when I open Visual Studio 2017 directly it works. But when I open a solution directly it doesn't work always. 

**http://vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a/**

Error: System.Diagnostics.Contracts.__ContractsRuntime+ContractException: Precondition failed: dataGrid != null
   at tomenglertde.ResXManager.View.Tools.ColumnManager.SetupColumns(DataGrid dataGrid, ResourceManager resourceManager, ResourceViewModel resourceViewModel, Configuration configuration) in C:\Agent\_work\9\s\ResXManager.View\Tools\ColumnManager.cs:line 65
   at tomenglertde.ResXManager.View.Visuals.ResourceView.ResourceManager_Loaded(Object sender, EventArgs e) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:line 67
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at tomenglertde.ResXManager.Model.ResourceManager.OnLoaded() in C:\Agent\_work\9\s\ResXManager.Model\ResourceManager.cs:line 165
   at tomenglertde.ResXManager.Model.ResourceManager.InternalLoad(IEnumerable`1 resourceFilesByDirectory) in C:\Agent\_work\9\s\ResXManager.Model\ResourceManager.cs:line 186
   at tomenglertde.ResXManager.Model.ResourceManager.Load(IList`1 allSourceFiles) in C:\Agent\_work\9\s\ResXManager.Model\ResourceManager.cs:line 71
   at tomenglertde.ResXManager.Model.ResourceManager.Reload(IList`1 sourceFiles) in C:\Agent\_work\9\s\ResXManager.Model\ResourceManager.cs:line 143
   at tomenglertde.ResXManager.View.Visuals.ResourceViewModel.Reload(Boolean forceFindCodeReferences) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceViewModel.cs:line 513

**Comment by judick341** [comment]
Ok, now with output of 1.15.1037.0:

ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception. ---> System.ArgumentException: Cannot add instance of type 'CommandRoutingBehavior' to a collection of type 'BehaviorCollection'. Only items of type 'T' are allowed.
   at System.Windows.FreezableCollection`1.Cast(Object value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml:line 1
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView..ctor(ExportProvider exportProvider, ThemeManager themeManager) in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml.cs:line 40
Error: System.Windows.Markup.XamlParseException: Collection property 'Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger'.'Actions' is null. ---> System.Xaml.XamlObjectWriterException: Collection property 'Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger'.'Actions' is null.
   at System.Xaml.XamlObjectWriter.WriteGetObject()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml:line 1
   at tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ICompositionHost compositionHost) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:line 55
Assembly location: C:\Users\dick\AppData\Local\Microsoft\VisualStudio\15.0_4ca776c5\Extensions\iisndssw.sld
Version: 1.15.1037.0
.NET Framework Version: 461310 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)

**Comment by tom-englert** [comment]
Can you try https://github.com/remcoros/DuplicateExtensionFinder

**Comment by Xgleich8** [comment]
Didn't work

**Comment by judick341** [comment]
Tried it too, didn't solve the problem.

[delete.txt](https://github.com/tom-englert/ResXResourceManager/files/1899007/delete.txt)
[duplicates.txt](https://github.com/tom-englert/ResXResourceManager/files/1899008/duplicates.txt)

**Comment by pinki** [comment]
@Xgleich8 I have the same behavior on my machine. When I open VS before I load the solution, everything's fine. When I open it loading the solution directly, the main tab is empty and/or VS crashes.

**Comment by ruigaspar** [comment]
Last ResXManager Version (1.15.1037.0) 

VS Community 2015 (14.0.25431.01): **Working**
VS Community 2017 (15.6.6): **Not Working**

Outputs--------------------
VS Community 2015:
```
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: C:\Users\ruiag\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\04gx3ql5.whx
Version: 1.15.1037.0
.NET Framework Version: 461308 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
```

VS Community 2017:
```
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception. ---> System.ArgumentException: Cannot add instance of type 'CommandRoutingBehavior' to a collection of type 'BehaviorCollection'. Only items of type 'T' are allowed.
   at System.Windows.FreezableCollection`1.Cast(Object value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml:line 1
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView..ctor(ExportProvider exportProvider, ThemeManager themeManager) in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml.cs:line 40
Assembly location: C:\Users\ruiag\AppData\Local\Microsoft\VisualStudio\15.0_1b8c0c76\Extensions\3mbcbi0b.iva
Version: 1.15.1037.0
.NET Framework Version: 461308 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
```

**Comment by vRITHNER** [comment]
When I install on my version 15.7.0 Preview 3, the extension is always disabled.
Even after Enable, restart, he still disabled. 
I did run the tool to find duplicated ones and delete them.
Still same issue
![2018-04-12_12h03_30](https://user-images.githubusercontent.com/238842/38670607-88ae8d4c-3e49-11e8-9d1a-5898c90a1721.png)

**Comment by tom-englert** [comment]
@vRITHNER then the VS extension installer cache seems to be messed up. Try to uninstall ResXManager and install again.

**Comment by ruigaspar** [comment]
Didn't solve the problem :(

```
Init: 371 ms
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: C:\Users\ruiag\AppData\Local\Microsoft\VisualStudio\15.0_1b8c0c76\Extensions\txrp0x1h.pwl
Version: 1.15.1038.0
.NET Framework Version: 461308 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception. ---> System.ArgumentException: Cannot add instance of type 'CommandRoutingBehavior' to a collection of type 'BehaviorCollection'. Only items of type 'T' are allowed.
   at System.Windows.FreezableCollection`1.Cast(Object value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml:line 1
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView..ctor(ExportProvider exportProvider, ThemeManager themeManager, VsixShellViewModel viewModel) in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml.cs:line 40

```

**Comment by tom-englert** [comment]
@ruigaspar Now this is the problem:
```
Assembly 'System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' loaded from file:///D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/Extensions/wyhgzaqi.mh1/System.Windows.Interactivity.dll
Assembly 'System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' loaded from file:///D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/PrivateAssemblies/System.Windows.Interactivity.DLL
```

can you check what is installed in `D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/Extensions/wyhgzaqi.mh1`?

**Comment by ruigaspar** [comment]
The extension is "GitHub.VisualStudio". I uninstall and worked, then reinstalled and stopped working again...

**Comment by tom-englert** [comment]
I can't see anything wrong on their side - and what happens if you remove `D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/PrivateAssemblies/System.Windows.Interactivity.DLL` ?

**Comment by tom-englert** [comment]
I have now installed GitHub for VisualStudio, and everything still works fine, so the problem is probably caused by the code loading `D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/PrivateAssemblies/System.Windows.Interactivity.DLL` (`.../Common7/IDE/PrivateAssemblies` does not exist on my machines)

**Comment by tom-englert** [comment]
I can confirm that adding `System.Windows.Interactivity.DLL` to the `.../Common7/IDE/PrivateAssemblies/` folder generates exactly the described behavior, and removing it from there fixes the problem.

**Comment by tom-englert** [comment]
@madskristensen I was just reading your post in the April 2018 - VS Partner Update, talking about the correct implementation of extensions.
Is there any advice how to distribute and use such shared stuff like the `System.Windows.Interactivity.DLL`?
Why does it behave different when a copy is in the `.../Common7/IDE/PrivateAssemblies` folder?
What is VS`s strategy behind this?

**Comment by madskristensen** [comment]
@tom-englert I've got no idea about that. Perhaps @alexeyler does?

**Comment by judick341** [comment]
I do not have the assembly that you mentioned in my PrivateAssemblies of the IDE folder. Unfortunately the problem is not solved for me.

**Comment by tom-englert** [comment]
@judick341 can you attach the log? "It does not work" is nothing I can work on.

**Comment by tom-englert** [comment]
@madskristensen I think I finally figured it out - it's been MEF loading the wrong assemblies. After loading them by my own and passing the assembly instead of the file name to MEF, the problem was gone.

**Comment by tom-englert** [comment]
@judick341 of course if you did not update and still use the old version, you wont see the fix.

**Comment by judick341** [comment]
Ok, that's the log for the new version 1043:
[ResXManager.log](https://github.com/tom-englert/ResXResourceManager/files/1918440/ResXManager.log)

**Comment by tom-englert** [comment]
@judick341 Can you try removing System.Windows.Interactivity.DLL from the GAC?

**Comment by judick341** [comment]
The DLLs are installed by the .NET-Framework and must not be removed by the user. I have one with version 4.0 and one with version 4.5 in the GAC. I tried to remove them with the tool GACBrowser anyway, but failed to remove them. 
I downloaded your code and have seen, that you use different versions of System.Windows.Interactivity in your solution. And: the DLL that is published is a version3.x ?! Maybe that's a problem?

**Comment by judick341** [comment]
YES!!!! Thank you very much for your support! 
I leave the version 1043 of the ResXManager installed. Great tool!

**Comment by tom-englert** [comment]
@vRITHNER use https://github.com/remcoros/DuplicateExtensionFinder

**Comment by Octavianbr** [comment]
My Visual Studio version is 15.9.6 and when I tried to install the latest version returns with an error (see below). The development server is off-line and does not have access to the internet so I have to do a manual install.



2019-02-20 10:55:50 AM - Initializing Install...
2019-02-20 10:55:50 AM - Extension Details...
2019-02-20 10:55:50 AM - 	Identifier      : 43b35fe0-1f30-48de-887a-68256474202a
2019-02-20 10:55:50 AM - 	Name            : ResXManager
2019-02-20 10:55:50 AM - 	Author          : tom-englert.de
2019-02-20 10:55:50 AM - 	Version         : 1.33.1745
2019-02-20 10:55:50 AM - 	Description     : The most popular tool to localize and manage all kind of applications with resx-based resources. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.
2019-02-20 10:55:50 AM - 	Locale          : en-US
2019-02-20 10:55:50 AM - 	MoreInfoURL     : https://github.com/tom-englert/ResXResourceManager
2019-02-20 10:55:50 AM - 	InstalledByMSI  : False
2019-02-20 10:55:50 AM - 	SupportedFrameworkVersionRange : [4.6.2,)
2019-02-20 10:55:50 AM - 
2019-02-20 10:55:50 AM - 	Supported Products : 
2019-02-20 10:55:50 AM - 		Microsoft.VisualStudio.Pro
2019-02-20 10:55:50 AM - 			Version : [14.0,17.0)
2019-02-20 10:55:50 AM - 		Microsoft.VisualStudio.Community
2019-02-20 10:55:50 AM - 			Version : [14.0,17.0)
2019-02-20 10:55:50 AM - 		Microsoft.VisualStudio.Enterprise
2019-02-20 10:55:50 AM - 			Version : [14.0,17.0)
2019-02-20 10:55:50 AM - 
2019-02-20 10:55:50 AM - 	References      : 
2019-02-20 10:55:50 AM - 		-------------------------------------------------------
2019-02-20 10:55:50 AM - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
2019-02-20 10:55:50 AM - 		Name         : Visual Studio MPF 11.0
2019-02-20 10:55:50 AM - 		Version      : [11.0,12.0)
2019-02-20 10:55:50 AM - 		MoreInfoURL  : 
2019-02-20 10:55:50 AM - 		Nested       : No
2019-02-20 10:55:50 AM - 
2019-02-20 10:55:50 AM - 
2019-02-20 10:55:50 AM - Searching for applicable products...
2019-02-20 10:55:54 AM - Found installed product - Global Location
2019-02-20 10:55:54 AM - Found installed product - ssms
2019-02-20 10:55:54 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
