### ISSUE TITLE
1.17.1072.0 Loading not correctly by opening VS 15.6.5 over Solution

### ISSUE THREAD

**Issue by Xgleich8** [tom-englert/ResXResourceManager#124]
Start VS 2017 directly not via *.sln - it works 

Version: 1.17.1072.0
.NET Framework Version: 461310 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception. ---> System.ArgumentException: Cannot add instance of type 'EntityFilter' to a collection of type 'BehaviorCollection'. Only items of type 'T' are allowed.
   at System.Windows.FreezableCollection`1.Cast(Object value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml:line 1
   at tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ICompositionHost compositionHost) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:line 55

**Comment by Xgleich8** [comment]
Found assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' already loaded from file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/PrivateAssemblies/Newtonsoft.Json.DLL.
Loaded assembly 'ResXManager.Infrastructure, Version=1.17.1072.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/name/AppData/Local/Microsoft/VisualStudio/15.0_5b7e72d3/Extensions/ao2402my.oe3/ResXManager.Infrastructure.DLL.
Loaded assembly 'ResXManager.Model, Version=1.17.1072.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/name/AppData/Local/Microsoft/VisualStudio/15.0_5b7e72d3/Extensions/ao2402my.oe3/ResXManager.Model.dll.
Loaded assembly 'ResXManager.Translators, Version=1.17.1072.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/name/AppData/Local/Microsoft/VisualStudio/15.0_5b7e72d3/Extensions/ao2402my.oe3/ResXManager.Translators.dll.
Loaded assembly 'ResXManager.View, Version=1.17.1072.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/name/AppData/Local/Microsoft/VisualStudio/15.0_5b7e72d3/Extensions/ao2402my.oe3/ResXManager.View.dll.
Loaded assembly 'ResXManager.VSIX, Version=1.17.1072.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/name/AppData/Local/Microsoft/VisualStudio/15.0_5b7e72d3/Extensions/ao2402my.oe3/ResXManager.VSIX.dll.
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: C:\Users\name\AppData\Local\Microsoft\VisualStudio\15.0_5b7e72d3\Extensions\ao2402my.oe3

**Comment by tom-englert** [comment]
@Xgleich8 can you try the latest version from here: http://vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a/

**Comment by Xgleich8** [comment]
It's running nice job
