### ISSUE TITLE
Error on opening visual studio add in

### ISSUE THREAD

**Issue by vishnu4** [tom-englert/ResXResourceManager#27]
Used this project for ages, worked fine.  Now after latest visual studio update i'm getting an error when i start it up.  I see the following error below:

ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Error: System.Windows.Markup.XamlParseException: Collection property 'Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger'.'Actions' is null. ---> System.Xaml.XamlObjectWriterException: Collection property 'Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger'.'Actions' is null.
   at System.Xaml.XamlObjectWriter.WriteGetObject()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml:line 1
   at tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ICompositionHost compositionHost) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:line 55
Assembly location: C:\Users\menow\AppData\Local\Microsoft\VisualStudio\15.0_7ea3f58a\Extensions\1tc1ejl2.ata
Version: 1.3.515.0

**Comment by tom-englert** [comment]
I can't reproduce this, can you try uninstall and reinstall again?

**Comment by vishnu4** [comment]
Yeah, still the same issue.  When the resx manager window pops up, the MAIN tab is just blank, doesn't show anything inside there.  The other 3 tabs all seem to exist and work properly though, oddly enough.  I can use the autotranslate page for example

**Comment by tom-englert** [comment]
After uninstall, did you verify that the extension is really gone? Sometimes the Vsix-installer fails to completely remove the older versions.  (see e.g. http://resxresourcemanager.codeplex.com/workitem/4730)

If you install the previous version, does this fix the problem?

**Comment by vishnu4** [comment]
Uninstall truly uninstalls, i don't see anything of the program after i uninstall (I've done it twice again to be sure).  I installed V1.2, which still has the same problem, which makes me think it's my data/files?  How would i go about debugging a bad resx file that might cause this?

**Comment by tom-englert** [comment]
Try to open the ResXManager window without having a solution open directly after starting VS - if that does not work either, it's not caused by bad resx file.

It rather looks like some problem with Microsoft.Expression.Interactions.dll/System.Windows.Interactivity.dll.
Can you debug your VS with another instance of VS, and see if these assemblies are loaded from the same folder as the ResXManager*.dll?

**Comment by vishnu4** [comment]
Yeah, you're right.  still comes up even if i don't have a solution open.  Sorry, i'm not very familiar with debugging extensions.  I tried attaching to the devenv.exe and setting my exception settings to break on every exception, but it didn't catch anything.
Is there a cache folder i could possibly try clearing out?

**Comment by tom-englert** [comment]
Can you check if all those assemblies are loaded from the same folder? (attach to devenv.exe, select Debug=>Windows=>Modules)
![image](https://user-images.githubusercontent.com/10229954/28431031-0c8db1ee-6d83-11e7-9d73-1d2b187cf3d5.png)

**Comment by vishnu4** [comment]
see attached images.  looks like expression comes from the GAC, and there are 2 versions of Interactivity  one from the GAC and one from your extension.

![a](https://user-images.githubusercontent.com/1782150/28433087-53ac917e-6d3f-11e7-82f3-811433127ca9.PNG)
![b](https://user-images.githubusercontent.com/1782150/28433088-53b0a160-6d3f-11e7-81a9-49b34814a4ca.PNG)

**Comment by tom-englert** [comment]
Try to remove them from the GAC - they should not be needed there.

**Comment by vishnu4** [comment]
Thank you so much.  the problem with telerik test studio, i had just downloaded a trial for that.
http://www.telerik.com/teststudio .  I actually just uninstalled that and it cleared the issue right up.  Thanks again for spending so much time helping me out here.

**Comment by tom-englert** [comment]
A good place to share your experience is here: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details :smile:

**Comment by tom-englert** [comment]
@vishnu4 I just tried to reproduce this, but it worked all fine - what version of the .Net framework do you have installed?

**Comment by vishnu4** [comment]
I have visual studio 2017 installed, so all the versions it comes with are there.  Plus the 4.6.2 and 4.7 targetting packs
