### ISSUE TITLE
VS 15.6.1 - NotImplementedException when loading main view

### ISSUE THREAD

**Issue by mgauthierUnicel** [tom-englert/ResXResourceManager#99]
On a clean install of VS 15.6.1, the main view throws the following exception.  The exception can be seen in the ResX Resource Manager output.
The exception is not occuring when the plugin was already installed prior to 15.6.1.

Error: System.Windows.Markup.XamlParseException: The method or operation is not implemented. ---> System.NotImplementedException: The method or operation is not implemented.
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType bamlType, Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16 typeId)
   at System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   at System.Windows.Baml2006.Baml2006Reader.Read()
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml:line 1
   at tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ICompositionHost compositionHost) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:line 55

**Comment by tom-englert** [comment]
@mgauthierUnicel did V1.13 fix this?

**Comment by mgauthierUnicel** [comment]
@tom-englert  no.  I still have the exception with 1.13.988.0 and VS 15.6.2

**Comment by tom-englert** [comment]
@mgauthierUnicel The stack trace does not point to ResXManager code, but to the systems xaml reader. Also this has never been reported by s.o. else, so I guess the problem is on your machine, only.
Have you tried updating the .Net Framework?

**Comment by mgauthierUnicel** [comment]
@tom-englert,  I have .NET Framework Version 461308 installed (.NET 4.7.1 of Windows 10 Fall Creators Update).

BTW, the full stack trace returned in the output was given.

**Comment by mgauthierUnicel** [comment]
I confirm that the fix you brought in #72 fixed my issue
